FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# base
RUN apt-get update && apt-get install -y \
    curl git unzip xz-utils zip libglu1-mesa openjdk-17-jdk wget \
    clang cmake ninja-build pkg-config libgtk-3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 user

# android
ENV ANDROID_SDK_ROOT=/opt/android-sdk
RUN mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools && \
    wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip && \
    unzip *tools*linux*.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools && \
    mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest && \
    rm *tools*linux*.zip

ENV FLUTTER_ROOT=/opt/flutter
RUN git clone https://github.com/flutter/flutter.git -b stable ${FLUTTER_ROOT}

RUN chown -R user:user ${ANDROID_SDK_ROOT} && \
    chown -R user:user ${FLUTTER_ROOT}

USER user

ENV PATH=${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:${FLUTTER_ROOT}/bin

# lisences
RUN yes | sdkmanager --licenses && \
    sdkmanager "platform-tools" "platforms;android-35" "platforms;android-36" "build-tools;34.0.0" "build-tools;28.0.3"

RUN git config --global --add safe.directory ${FLUTTER_ROOT} && \
    flutter config --no-analytics && \
    flutter doctor
