// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUe8e_fjLQqzcT3h1den3DD-O_QWObwYs',
    appId: '1:913565537458:web:225ef7360992f1a816e5ab',
    messagingSenderId: '913565537458',
    projectId: 'chat-app-a0f04',
    authDomain: 'chat-app-a0f04.firebaseapp.com',
    storageBucket: 'chat-app-a0f04.firebasestorage.app',
    measurementId: 'G-LTGXWMKGE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrqQUkkKUEZYwBYFDeN6Jxt4WJUs_UzQ',
    appId: '1:913565537458:android:c005561cf7d7c7c716e5ab',
    messagingSenderId: '913565537458',
    projectId: 'chat-app-a0f04',
    storageBucket: 'chat-app-a0f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsaWAzTByCSEJpOGItJPyCAfQv6w80-Rk',
    appId: '1:913565537458:ios:84c9306e09158b5516e5ab',
    messagingSenderId: '913565537458',
    projectId: 'chat-app-a0f04',
    storageBucket: 'chat-app-a0f04.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsaWAzTByCSEJpOGItJPyCAfQv6w80-Rk',
    appId: '1:913565537458:ios:84c9306e09158b5516e5ab',
    messagingSenderId: '913565537458',
    projectId: 'chat-app-a0f04',
    storageBucket: 'chat-app-a0f04.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUe8e_fjLQqzcT3h1den3DD-O_QWObwYs',
    appId: '1:913565537458:web:89497b2024b60e2e16e5ab',
    messagingSenderId: '913565537458',
    projectId: 'chat-app-a0f04',
    authDomain: 'chat-app-a0f04.firebaseapp.com',
    storageBucket: 'chat-app-a0f04.firebasestorage.app',
    measurementId: 'G-1HQWZ7FPX3',
  );
}
