server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Enable gzip compression
    gzip on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript application/wasm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache control for static assets
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Cache control for javascript, css and wasm
    location ~* \.(?:css|js|wasm)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Disable cache for service worker to ensure updates
    location = /flutter_service_worker.js {
        expires off;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
